# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: Terraform Plugin Framework Bug Reports and Feature Requests
    url: https://github.com/hashicorp/terraform-plugin-framework/issues
    about: GitHub issues in this repository are only intended for bug reports and feature requests of common use case validators. Submit bug reports and feature request for the Terraform Plugin Framework to its separate repository issue tracker.
  - name: Terraform Plugin Framework Questions
    url: https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk
    about: Please ask and answer SDK related questions through the Terraform Plugin SDK section of HashiCorp Discuss.
  - name: Terraform Provider Questions
    url: https://discuss.hashicorp.com/c/terraform-providers/31
    about: Please ask and answer questions through the Terraform Provider section of HashiCorp Discuss.
  - name: Terraform Language or Workflow Questions
    url: https://discuss.hashicorp.com/c/terraform-core
    about: Please ask and answer language or workflow related questions through the Terraform Core section of HashiCorp Discuss.
